apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  labels:
    app: javaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: newcontainer
        image: 889796695136.dkr.ecr.ap-south-1.amazonaws.com/my-ecr-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
    apiVersion: v1
kind: Service
metadata:
  name: javaapp
  labels:
    name: javaapp
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
